config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  resources :blogs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

    #ブログ画面、一覧表示
    def index
      @blogs=Blog.all
    end


    # 新規画面表示
    def new
      if params[:back]
        @blog = Blog.new(blog_params)
      else
        @blog=Blog.new
      end
    end


    # 更新画面……情報は「set_blog」で取得
    def edit
  #    binding.pry
    end

    # 閲覧画面……情報は「set_blog」で取得
    def show
    end


    #新規登録処理
    def create

      @blog = Blog.new(blog_params)

      respond_to do |format|
        if @blog.save

          #処理後は一覧画面に移動
          format.html { redirect_to blogs_path, notice: '登録しました。' }
        else
          format.html { render :new }
        end
      end
    end


      # 更新処理……情報は「set_blog」で取得
      def update
        respond_to do |format|
          if @blog.update(blog_params)

            #処理後は投稿内容確認画面に移動
            format.html { redirect_to blogs_path, notice: '更新に成功しました。' }
          else
            format.html { render :edit }
          end
        end
      end


      # 削除処理
      def destroy
        @blog.destroy
        respond_to do |format|
          format.html { redirect_to blogs_path, notice: '削除に成功しました。' }
          format.json { head :no_content }
        end
      end



    private

    def set_blog

      @blog = Blog.find(params[:id])
    end


    #DB更新用にパラメータセット
    def blog_params
      params.require(:blog).permit(:title,:content)
    end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <%= form.submit %>

<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを作成する</h2>


<%= render 'form' %>

<div></div>

<%= link_to "ブログを削除する", blog_path(@blog.id) ,
 method: :delete, data: { confirm: '本当に編集していいですか？' }  %>


<div></div>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to 'ブログ内容を確認,編集する', edit_blog_path(blog.id) %></td>
  </tr>
<% end %>

</table>


<div></div>
<div></div>

<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>


<%= render 'form' %>

<div></div>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
<h1>アプリを選択してください  tesuto</h1>


<%= link_to 'ブログへ', blogs_path %>